### USUARIOS REQUESTS ###

POST http://localhost:3000/api/usuarios/news
Content-Type: application/json

[
  {
    "nombre": "Juan",
    "apellido": "Pérez",
    "email": "juan.perez@example.com",
    "psw": "12345",
    "direccion": "Calle 123, Ciudad XYZ",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f619f" },
    "id_sucursal": null
  },
  {
    "nombre": "Juana",
    "apellido": "Taliercio",
    "email": "juana@example.com",
    "psw": "12345",
    "direccion": "dadas 123",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f61a0" },
    "id_sucursal": null
  },
  {
    "nombre": "Paco",
    "apellido": "Ponce",
    "email": "picopala@example.com",
    "psw": "12345",
    "direccion": "dadaasdf 5",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f61a1" },
    "id_sucursal": "679d40bd009c4a8531e5eae7"
  },
  {
    "nombre": "Octavio",
    "apellido": "Romero",
    "email": "octavio@example.com",
    "psw": "12345",
    "direccion": "dadaasdf 5",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f61a1" },
    "id_sucursal": "679d40bd009c4a8531e5eae8"
  },
  {
    "nombre": "Carolina",
    "apellido": "Rombolá",
    "email": "caro@example.com",
    "psw": "12345",
    "direccion": "asd 522",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f61a2" },
    "id_sucursal": null
  },
  {
    "nombre": "Lilia",
    "apellido": "Mallo",
    "email": "lili@example.com",
    "psw": "12345",
    "direccion": "564sda",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f61a2" },
    "id_sucursal": null
  }
]

###

POST http://localhost:3000/api/usuarios/new
Content-Type: application/json

{
    "nombre": "El nuevo",
    "apellido": "deEsta",
    "email": "agar.ramessta@example.com",
    "psw": "12345",
    "direccion": "asasdf",
    "telefono": "1234567890",
    "rol": { "id_rol": "679d40bca61fa54e261f61a1" }, //VENDEDOR
    "id_sucursal": "679d40bd009c4a8531e5eae6" //SUCURSAL#1
}

###

GET http://localhost:8080/usuarios
Content-Type: application/json

###

GET http://localhost:8080/usuarios/17
Content-Type: application/json

###

GET http://localhost:8080/usuarios/emails
Content-Type: application/json

###

GET http://localhost:8080/usuarios/email/?email=madev@gmail.com
Content-Type: application/json

###

DELETE  http://localhost:8080/usuarios/18
Content-Type: application/json

###

GET http://localhost:8080/usuarios/emails
Content-Type: application/json

###

DELETE  http://localhost:8080/usuarios/23
Content-Type: application/json