### VUELOS REQUESTS ###

GET http://localhost:3000/api/vuelos
Content-Type: application/json

###

GET http://localhost:3000/api/vuelos/679db51a9105fb4c87f78411
Content-Type: application/json

###

POST http://localhost:3000/api/vuelos/new
Content-Type: application/json

{
  "fecha": "2025-05-25",
  "hora": "22:50",
  "origen": "Argentina, Buenos Aires",
  "destino": "España, Madrid",
  "plazasTotales": 50,
  "plazasTurista": 50
}

###

POST http://localhost:3000/api/vuelos/news
Content-Type: application/json

[
  {
    "fecha": "2025-05-25",
    "hora": "22:50",
    "origen": "Argentina, Buenos Aires",
    "destino": "España, Madrid",
    "plazasTotales": 50,
    "plazasTurista": 50
  },
  {
    "fecha": "2025-06-03",
    "hora": "13:10",
    "origen": "España, Madrid",
    "destino": "Argentina, Buenos Aires",
    "plazasTotales": 20,
    "plazasTurista": 80
  }
]

###

PUT http://localhost:3000/api/vuelos/679db51a9105fb4c87f78411
Content-Type: application/json

  {
    "fecha": "2025-05-25",
    "hora": "22:50",
    "origen": "Argentina, Buenos Aires",
    "destino": "España, Madrid",
    "plazasTotales": 45,
    "plazasTurista": 55
  }

###

DELETE http://localhost:3000/api/vuelos/679db4ee9105fb4c87f7840a